// baseline_cnn_params.vh - BaselineCNN (scheme A) hardware parameter header.
// Generated by model/export_baseline_cnn_hardware.py. Do not hand-edit.
// Every multiplier is positive and fits a signed 32-bit value (31-bit magnitude).

// ---- input geometry ----
localparam IN_CH = 1;
localparam IN_H  = 28;
localparam IN_W  = 28;

// ---- conv / pool geometry (3x3, pad 1, stride 1; 2x2 maxpool) ----
localparam KERNEL       = 3;
localparam PADDING      = 1;
localparam STEM_OC      = 16;
localparam STEM_H       = 28;
localparam STEM_W       = 28;
localparam STEM_POOL_H  = 14;
localparam STEM_POOL_W  = 14;
localparam CONV2_OC     = 32;
localparam CONV2_H      = 14;
localparam CONV2_W      = 14;
localparam CONV2_POOL_H = 7;
localparam CONV2_POOL_W = 7;
localparam CONV3_OC     = 32;
localparam CONV3_H      = 7;
localparam CONV3_W      = 7;

// ---- global average pool ----
localparam GAP_CH       = 32;   // conv3 output channels (GAP input)
localparam GAP_DIVISOR  = 49;   // integer sum / 49, round-half-away-from-zero

// ---- fc ----
localparam FC_OC  = 10;
localparam FC_IC  = 32;   // = GAP_CH

// ---- fixed-point requantisation (acc * mult) >> shift -------
localparam STEM_REQUANT_MULT  = 32'h7A999012;  // 2056884242
localparam STEM_REQUANT_SHIFT = 38;
localparam CONV2_REQUANT_MULT = 32'h416335B9;  // 1097020857
localparam CONV2_REQUANT_SHIFT = 38;
localparam CONV3_REQUANT_MULT = 32'h4D6CC8EC;  // 1298974956
localparam CONV3_REQUANT_SHIFT = 38;

// ---- memory depths (weights OIHW / fc OI; biases linear) ----
localparam STEM_WEIGHT_DEPTH  = 144;
localparam CONV2_WEIGHT_DEPTH = 4608;
localparam CONV3_WEIGHT_DEPTH = 9216;
localparam FC_WEIGHT_DEPTH    = 320;
localparam STEM_BIAS_DEPTH    = 16;
localparam CONV2_BIAS_DEPTH   = 32;
localparam CONV3_BIAS_DEPTH   = 32;
localparam FC_BIAS_DEPTH      = 10;

// ---- integer range bounds (clamp-saturate, no wraparound) ----
localparam ACC_INT32_MIN = -32'h80000000;
localparam ACC_INT32_MAX =  32'h7FFFFFFF;
localparam UINT8_MAX_VAL = 8'hFF;
