// Generated by model.snn.export_params. Do not edit manually.
`ifndef ONN_SNN_PARAMS_SVH
`define ONN_SNN_PARAMS_SVH

localparam int unsigned SNN_TIME_STEPS = 4;
localparam int unsigned SNN_STATE_GUARD_BITS = 4;

localparam int unsigned CONV1_WEIGHT_BITS = 8;
localparam int unsigned CONV1_WEIGHT_COUNT = 144;
localparam int unsigned CONV1_RAW_ACC_BITS = 12;
localparam int unsigned CONV1_CURRENT_BITS = 16;
localparam int unsigned LIF1_MEM_BITS = 18;
localparam int unsigned LIF1_THRESHOLD_BITS = 10;
localparam int unsigned LIF1_THRESHOLD = 939;

localparam int unsigned CONV2_WEIGHT_BITS = 8;
localparam int unsigned CONV2_WEIGHT_COUNT = 4608;
localparam int unsigned CONV2_RAW_ACC_BITS = 16;
localparam int unsigned CONV2_CURRENT_BITS = 20;
localparam int unsigned LIF2_MEM_BITS = 22;
localparam int unsigned LIF2_THRESHOLD_BITS = 11;
localparam int unsigned LIF2_THRESHOLD = 1715;

localparam int unsigned READOUT_WEIGHT_BITS = 8;
localparam int unsigned READOUT_WEIGHT_COUNT = 5120;
localparam int unsigned READOUT_CURRENT_BITS = 17;
localparam int unsigned WEIGHTED_LOGITS_BITS = 21;

localparam int unsigned TEMPORAL_COEFF_0 = 5;
localparam int unsigned TEMPORAL_COEFF_1 = 4;
localparam int unsigned TEMPORAL_COEFF_2 = 3;
localparam int unsigned TEMPORAL_COEFF_3 = 2;

`endif
