"""Export the fixed seed-17 SNN integer parameters for RTL development."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

import torch

from model.snn.integer_reference import IntegerSNNReference, IntegerWidths


ROOT = Path(__file__).resolve().parents[2]
DEPLOYMENT_SEED = 17
CHECKPOINT_RELATIVE_PATH = Path(
    "experiments/snn/conv_small/results/event_regularization/"
    "beta_0p5_lambda_0p10_seed17/best_model.pt"
)
EXPECTED_CHECKPOINT_SHA256 = (
    "ecd4fa940c229bb9c717f33d68db2cdaf45ad6b83b48d597465d5431d8c845e6"
)
DEFAULT_EXPORT_DIR = Path(__file__).resolve().parent / "export"

WEIGHT_EXPORTS = {
    "conv1": ("conv1.weight", "conv1_weight.mem"),
    "conv2": ("conv2.weight", "conv2_weight.mem"),
    "readout": ("readout.weight", "readout_weight.mem"),
}


def sha256_file(path: Path) -> str:
    """Return the lowercase SHA256 digest of a file."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_deployment_state() -> tuple[dict[str, torch.Tensor], str]:
    """Load the sole deployment checkpoint after verifying its frozen identity."""
    checkpoint = ROOT / CHECKPOINT_RELATIVE_PATH
    digest = sha256_file(checkpoint)
    if digest != EXPECTED_CHECKPOINT_SHA256:
        raise RuntimeError(
            f"deployment checkpoint hash mismatch: expected "
            f"{EXPECTED_CHECKPOINT_SHA256}, got {digest}"
        )
    state = torch.load(checkpoint, map_location="cpu", weights_only=True)
    expected_keys = {value[0] for value in WEIGHT_EXPORTS.values()}
    if set(state) != expected_keys:
        raise RuntimeError(
            f"unexpected deployment checkpoint keys: {sorted(state)}"
        )
    return state, digest


def write_int8_mem(path: Path, tensor: torch.Tensor) -> None:
    """Write one two's-complement byte per line in contiguous tensor order."""
    if tensor.dtype != torch.int8:
        raise TypeError(f"{path.name} requires an INT8 tensor")
    values = tensor.detach().cpu().contiguous().view(-1).to(torch.int16).tolist()
    path.write_text(
        "".join(f"{value & 0xFF:02X}\n" for value in values), encoding="ascii"
    )


def read_int8_mem(path: Path, shape: tuple[int, ...] | list[int]) -> torch.Tensor:
    """Read an exported memory file back into a signed INT8 tensor."""
    words = [line.strip() for line in path.read_text(encoding="ascii").splitlines()]
    if any(len(word) != 2 for word in words):
        raise ValueError(f"{path.name} must contain one two-digit byte per line")
    try:
        unsigned = [int(word, 16) for word in words]
    except ValueError as error:
        raise ValueError(f"{path.name} contains a non-hexadecimal byte") from error
    expected_count = math.prod(shape)
    if len(unsigned) != expected_count:
        raise ValueError(
            f"{path.name} contains {len(unsigned)} bytes, expected {expected_count}"
        )
    signed = [value if value < 128 else value - 256 for value in unsigned]
    return torch.tensor(signed, dtype=torch.int8).reshape(tuple(shape))


def _raw_accumulator_bits(fan_in: int) -> int:
    """Bits for the exact worst-case sum of ``fan_in`` signed INT8 weights."""
    maximum = fan_in * 127
    return maximum.bit_length() + 1


def _params_svh(reference: IntegerSNNReference) -> str:
    widths = reference.widths
    thresholds = reference.thresholds
    coefficients = reference.temporal_coefficients
    return f"""// Generated by model.snn.export_params. Do not edit manually.
`ifndef ONN_SNN_PARAMS_SVH
`define ONN_SNN_PARAMS_SVH

localparam int unsigned SNN_TIME_STEPS = {reference.time_steps};
localparam int unsigned SNN_STATE_GUARD_BITS = {reference.state_fractional_guard_bits};

localparam int unsigned CONV1_WEIGHT_BITS = 8;
localparam int unsigned CONV1_WEIGHT_COUNT = 144;
localparam int unsigned CONV1_RAW_ACC_BITS = {_raw_accumulator_bits(9)};
localparam int unsigned CONV1_CURRENT_BITS = {widths.conv1_current};
localparam int unsigned LIF1_MEM_BITS = {widths.mem1};
localparam int unsigned LIF1_THRESHOLD_BITS = {thresholds['conv1.weight'].bit_length()};
localparam int unsigned LIF1_THRESHOLD = {thresholds['conv1.weight']};

localparam int unsigned CONV2_WEIGHT_BITS = 8;
localparam int unsigned CONV2_WEIGHT_COUNT = 4608;
localparam int unsigned CONV2_RAW_ACC_BITS = {_raw_accumulator_bits(16 * 3 * 3)};
localparam int unsigned CONV2_CURRENT_BITS = {widths.conv2_current};
localparam int unsigned LIF2_MEM_BITS = {widths.mem2};
localparam int unsigned LIF2_THRESHOLD_BITS = {thresholds['conv2.weight'].bit_length()};
localparam int unsigned LIF2_THRESHOLD = {thresholds['conv2.weight']};

localparam int unsigned READOUT_WEIGHT_BITS = 8;
localparam int unsigned READOUT_WEIGHT_COUNT = 5120;
localparam int unsigned READOUT_CURRENT_BITS = {widths.readout_current};
localparam int unsigned WEIGHTED_LOGITS_BITS = {widths.weighted_logits};

localparam int unsigned TEMPORAL_COEFF_0 = {coefficients[0]};
localparam int unsigned TEMPORAL_COEFF_1 = {coefficients[1]};
localparam int unsigned TEMPORAL_COEFF_2 = {coefficients[2]};
localparam int unsigned TEMPORAL_COEFF_3 = {coefficients[3]};

`endif
"""


def export_parameters(output_dir: Path = DEFAULT_EXPORT_DIR) -> dict:
    """Export deterministic RTL inputs and return their manifest."""
    state, checkpoint_digest = load_deployment_state()
    widths = IntegerWidths.for_guard_bits(4, readout_current=17)
    reference = IntegerSNNReference(state, guard_bits=4, widths=widths)
    output_dir.mkdir(parents=True, exist_ok=True)

    weights = {}
    exports = {}
    for export_name, (state_key, filename) in WEIGHT_EXPORTS.items():
        tensor = reference.weights[state_key].to(torch.int8)
        path = output_dir / filename
        write_int8_mem(path, tensor)
        spec = reference.specs[state_key]
        weights[export_name] = {
            "state_dict_key": state_key,
            "shape": list(tensor.shape),
            "element_count": tensor.numel(),
            "dtype": "int8",
            "signed": True,
            "layout": "PyTorch contiguous row-major; indices follow the recorded shape",
            "scale": spec.scale,
            "zero_point": spec.zero_point,
            "qmin": spec.qmin,
            "qmax": spec.qmax,
            "observed_min": int(tensor.min().item()),
            "observed_max": int(tensor.max().item()),
            "file": filename,
            "file_sha256": sha256_file(path),
        }
        exports[state_key] = filename

    metadata = reference.quantization_metadata()
    params_path = output_dir / "params.svh"
    params_path.write_text(_params_svh(reference), encoding="utf-8", newline="\n")
    exports["rtl_constants"] = params_path.name

    manifest = {
        "format_version": 1,
        "deployment_identity": "frozen-t4-snn-seed17-guard4-int17",
        "seed": DEPLOYMENT_SEED,
        "checkpoint_path": CHECKPOINT_RELATIVE_PATH.as_posix(),
        "checkpoint_sha256": checkpoint_digest,
        "selection_basis": {
            "policy": "highest frozen validation accuracy, with deterministic checkpoint reproduction; test accuracy was not used for selection",
            "best_epoch": 18,
            "best_validation_accuracy_percent": 95.2,
            "deterministic_rerun_checkpoint_sha256": checkpoint_digest,
        },
        "memory_file_format": {
            "word_bits": 8,
            "radix": "hexadecimal",
            "lines": "one two's-complement byte per line, uppercase, no prefix",
            "tensor_order": "contiguous row-major in the shape recorded for each weight",
        },
        "weights": weights,
        "thresholds": {
            "lif1": {
                "source_weight": "conv1.weight",
                "integer": reference.thresholds["conv1.weight"],
                "unsigned_bits": reference.thresholds["conv1.weight"].bit_length(),
                "state_scale": reference.specs["conv1.weight"].scale / 16,
            },
            "lif2": {
                "source_weight": "conv2.weight",
                "integer": reference.thresholds["conv2.weight"],
                "unsigned_bits": reference.thresholds["conv2.weight"].bit_length(),
                "state_scale": reference.specs["conv2.weight"].scale / 16,
            },
        },
        "bit_widths": {
            "input_spike": {"bits": 1, "signed": False},
            "weight": {"bits": 8, "signed": True},
            "conv1_raw_accumulator": {"bits": _raw_accumulator_bits(9), "signed": True},
            "conv1_current": {"bits": widths.conv1_current, "signed": True},
            "lif1_membrane": {"bits": widths.mem1, "signed": True},
            "conv2_raw_accumulator": {"bits": _raw_accumulator_bits(144), "signed": True},
            "conv2_current": {"bits": widths.conv2_current, "signed": True},
            "lif2_membrane": {"bits": widths.mem2, "signed": True},
            "readout_current": {"bits": widths.readout_current, "signed": True},
            "weighted_logits": {"bits": widths.weighted_logits, "signed": True},
        },
        "hidden_state_guard_bits": reference.state_fractional_guard_bits,
        "temporal_coefficients": list(reference.temporal_coefficients),
        "quantization_rule": {
            "weights": "per-tensor symmetric INT8, scale=max(abs(W))/127, zero-point=0",
            "rounding": metadata["rounding"],
            "overflow": metadata["overflow"],
            "threshold_compare": metadata["threshold_compare"],
            "reset": metadata["reset"],
        },
        "exports": exports,
    }
    manifest_path = output_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_EXPORT_DIR)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest = export_parameters(args.output_dir)
    print(json.dumps({
        "seed": manifest["seed"],
        "checkpoint_sha256": manifest["checkpoint_sha256"],
        "output_dir": str(args.output_dir),
        "exports": manifest["exports"],
    }, indent=2))


if __name__ == "__main__":
    main()
